export enum KEY_INJECTION {
    VOUCHER_REPOSITORY_CONTRACT = "",
    PARTICIPANTE_REPOSITORY_CONTRACT = "",
    CAMPANHA_REPOSITORY_CONTRACT = "",
    ROLETA_REPOSITORY_CONTRACT = "",

    RETAGUARDA_DATA_SOURCE = "VAR_DATA_SOURCE_CONNECTION",
};